### ISSUE TITLE
Fails on finding series name

### ISSUE THREAD

**Issue by tpikonen** [fennekki/supla-rssproxy#1] opened 2019-05-10 06:33 UTC
supla-rssproxy now crashes on trying to parse files from supla.fi. It seems there's some obfuscation added to the HTML:

```
$ python3 supla_rssproxy/main.py --config-file conf.json
{'own_url': 'http://localhost/', 'target_dir': './', 'podcasts': {'hskl': 'https://www.supla.fi/supla/3390661'}}
[2019-05-10 09:25:00.218561] Scraping 3390661
Traceback (most recent call last):
  File "supla_rssproxy/main.py", line 240, in <module>
    main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "supla_rssproxy/main.py", line 229, in main
    rss_data = get_rss_data(supla_id)
  File "supla_rssproxy/main.py", line 86, in get_rss_data
    series_name = html.find(".//h2[@class='series-info__title']").text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by fennekki** [comment] 2019-05-10 06:49
Hmm, yeah, the scraping was always kind of fragile, so I expected this'd happen eventually. I'll look into it

**Comment by fennekki** [comment] 2019-05-10 07:30
Alright, interesting, looks like they actually directly embed a chunk of JSON that contains at least some of the informaiton we need in the pages, now. This feels like it should make the scraping even easier. I'll try fixing this later in the evening.

**Comment by fennekki** [comment] 2019-05-10 23:45
Looks like there's no trivial way to scrape the episode urls anymore without javascript, so this could take a while

**Comment by fennekki** [comment] 2019-05-13 19:47
I want to clarify that the issue is not so much finding the series name - that should be fixed in 88b021a9a99a9cb0a66edb1263c324d7783dd1aa - but that the site no longer seems to load the list of episodes on each page without javascript. I'm trying to figure out where to find those, but this is a low intensity project for me, so please feel free to help if you have anything useful.

**Comment by fennekki** [comment] 2019-05-28 21:13
I've found an API endpoint that seems to expose this information without scraping needed. This should simplify the whole thing quite a bit, since we can just directly get all the information we want from the API - I'll try getting a fix out tonight.

**Comment by fennekki** [comment] 2019-05-28 22:05
@tpikonen please check if f080452d9dc358784611f63f52862b1559bed144 (current head of the `issue-1-fix` branch) fixed the issue for you. In my tests it seems to function as expected.

**Comment by tpikonen** [comment] 2019-05-29 20:34
Works fine here. Thanks for the fix.

**Closed** 2019-05-29 21:41 UTC
Labels: bug
